server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tjuniversitywzy/spring-cloud-study-applications.git #git仓库名称http
          username: 1016680285@qq.com
          password: wzyzero123
      #       搜索目录,仓库内部路径
          search-paths:
            /**
          skip-ssl-validation: true
      #      读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka