server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#设置feign客户端超时时间，适用于网络状况正常的情况下
ribbon:
  #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeOut: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeOut: 5000;
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
logging:
  level:
    #feign日志以什么级别监控哪个接口
    org.atguigu.springcloud.service.PaymentFeignService: debug